### ISSUE TITLE
How to configure on ST3?

### ISSUE THREAD

**Issue by montogeek** [ternjs/tern_for_sublime#78]
I followed the instructions, installed everything, set the configuration using Preferences.sublime-settings file but nothing happens.
My configuration:

```
"tern_argument_hints_type": "tooltip",
    "tern_argument_completion": true
```

**Comment by marijnh** [comment]
Any errors in the ctrl-~ console? Did you double-check the directory structure (the plugin directory should be under `Packages`)

**Comment by cloverich** [comment]
(On OSX) I followed Marijn's advice to check the console and discovered an error: I was installing tern in `/Applications/Sublime\ Text.app/Contents/MacOS/Packages/`, a mostly unused directory, instead of the expected `~/Library/Application Support/Sublime Text 3/ Packages` -- the Packages folder under my home directory (where all the other packages I"ve been installing are). Maybe you are doing the same thing @montogeek? Note I had sublime text open when I installed and ST immediately picked up a new package.
